apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cm-nginx
  labels:
    app: cm-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-nginx
  template:
    metadata:
      labels:
        app: cm-nginx
    spec:
      containers:
      - name: cm-nginx
        image: docker-registry-default.ai-dev.asiainfo.com/aura/nginx:0.02
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: "/mnt/data/confm/"
            name: confm
          - mountPath: "/mnt/data/nginx/"
            name: nginx-data
      nodeSelector:
        zone: east
      volumes:
        - name: confm
          configMap:
            name: nginx-config
            items:
            - key: cm.txt
              path: cm.txt
            - key: cm2.txt
              path: cm2.txt
            - key: cm1.txt
              path: 1/cm1.txt
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-data
# Noted: used host path directly here will cause service couldn't be connected successfully
# used persistent volume instead
#          hostPath:
#            path: /mnt/data/nginx/
#            type: DirectoryOrCreate
                       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cm-nginx-svc
  name: cm-nginx-svc
spec:
  selector:
    app: cm-nginx
  ports:
  - name: cm-nginx
    port: 10080
    targetPort: 80
  #type: NodePort
  externalIPs:
    - 10.1.241.56
    - 10.1.241.54

