apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-dyn-claim
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi 
