apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: hawcass-claim 
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 10Gi 
