apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: registry-claim
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 100Gi 
