apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-single
provisioner: kubernetes.io/glusterfs
parameters:
# since k8s 1.5, endpoint is not necessary for dynamic provisioning
#  endpoint: "heketi-ep"  
# volume type is key parameters for setting up volume
  resturl: "http://10.1.241.51:8080"  
  restuser: "admin"  
  restuserkey: "storage secret"  
  secretName: "heketi-secret"
  secretNameSpace: "brokers"
  volumetype: "none"

---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: brokers
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
  key: a0xkODM0ZGFkRXNmd2N2
type: kubernetes.io/glusterfs

#---
#kind: Endpoints
#apiVersion: v1
#metadata:
#  name: heketi-ep
#  labels:
#    component: gluster-dyn
#subsets:
#  - addresses:
#      - ip: 10.1.241.51
#    ports:
#      - port: 1
#  - addresses:
#      - ip: 10.1.241.52
#    ports:
#      - port: 1
