# permissions to do viewer guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook-viewer-role
rules:
- apiGroups:
  - webapp.guestbook.io
  resources:
  - guestbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.guestbook.io
  resources:
  - guestbooks/status
  verbs:
  - get
